//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje_blog.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gonderiler
    {
        public int gonderiid { get; set; }
        public string baslik { get; set; }
        public string gonderi { get; set; }
        public Nullable<System.DateTime> saat { get; set; }
        public string resim { get; set; }
        public Nullable<int> katid { get; set; }
        public Nullable<int> tiklanma_say { get; set; }
        public Nullable<int> begenme { get; set; }
        public Nullable<int> asagilama { get; set; }
    
        public virtual kategoriler kategoriler { get; set; }
    }
}
