//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje_blog.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicilar
    {
        public int id { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string mail { get; set; }
        public string sifre { get; set; }
        public string hakkinda { get; set; }
        public string telefon { get; set; }
        public string resim { get; set; }
        public string nick { get; set; }
    }
}
