//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje_blog.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesajlar
    {
        public int id { get; set; }
        public string mesaj { get; set; }
        public Nullable<System.DateTime> saat { get; set; }
        public string isim { get; set; }
        public Nullable<bool> okundu { get; set; }
        public string mail { get; set; }
        public string konu { get; set; }
    }
}
